[package]
name = "random-wallpaper"
version = "0.1.0"
authors = ["Pedro Scaff <pedro@scaff.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
dirs = "2.0.2"
